blogs-before/config/routes.rb
Blogs::Application.routes.draw do
  resources :blogs
  resources :articles
  root to: 'blogs#index'
end

blogs-before/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :blog
end

blogs-before/app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :articles
end

blogs-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

blogs-before/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
end

blogs-before/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(params[:blog])
    if @blog.save
      redirect_to @blog, notice: "Successfully created blog."
    else
      render :new
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update_attributes(params[:blog])
      redirect_to root_url, notice: "Successfully updated blog."
    else
      render :edit
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to root_url, notice: "Successfully destroyed article."
  end
end

blogs-before/app/helpers/application_helper.rb
module ApplicationHelper
end

blogs-before/app/helpers/articles_helper.rb
module ArticlesHelper
end

blogs-before/app/helpers/blogs_helper.rb
module BlogsHelper
end

blogs-before/app/views/articles/show.html.erb
<h1><%= @article.name %></h1>

<%= simple_format @article.content %>

<p><%= link_to "Back to Articles", @article.blog %></p>

blogs-before/app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <% if @blog.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subdomain %><br />
    <%= f.text_field :subdomain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blogs-before/app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

blogs-before/app/views/blogs/index.html.erb
<h1>Blogs</h1>

<% @blogs.each do |blog| %>
  <div class="blog">
    <h2><%= link_to blog.name, blog %></h2>
    <div class="actions">
      <%= link_to "Edit", edit_blog_path(blog) %> |
      <%= link_to "Destroy", blog, confirm: 'Are you sure?', method: :delete %>
    </div>
  </div>
<% end %>

<p><%= link_to "New Blog", new_blog_path %></p>

blogs-before/app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

blogs-before/app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1>

<div id="articles">
<% @blog.articles.each do |article| %>
  <h2><%= link_to article.name, article %></h2>
  <%= simple_format(article.content) %>
<% end %>
</div>

blogs-before/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>